spring.application.name=traintracker
spring.datasource.url=jdbc:mysql://localhost:3306/traintracker
spring.datasource.username=root
spring.datasource.password=yash#1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
